#-------------------------------------------------------------------
#        D - F L A T   M A K E F I L E  -  Borland C++ 3.1 and 4.0
#-------------------------------------------------------------------
VERNAME := $(word 3, $(shell type,\orangec\src\version.h))
VERNAME := $(subst ",,$(VERNAME))
VERNAME := $(subst .,,$(VERNAME))

all : install.exe dopack

#-------------------------------------------------------------------
#  Delete the TESTING macro to eliminate the Reload
#  Help file selection on the Help menu.
#-------------------------------------------------------------------
TESTING = TESTING_DFLAT
#-------------------------------------------------------------------
#  This macro builds the full D-Flat system with all options enabled.
#  Comment it out for a minimum system or selectively
#  comment out the #defines at the top of dflat.h.
#-------------------------------------------------------------------
FULL = BUILD_FULL_DFLAT
#-------------------------------------------------------------------

#------------------------------------------------
# NOTE: Delete the DEBUG and LINKDEBUG macros to 
# build without debugging information in the .EXE
#------------------------------------------------
DEBUG = -v
LINKDEBUG = /DEB /Map
#------------------------------------------------
COMPILE = cc386 $(DEBUG) -D$(TESTING) -D$(FULL) -DBCPP +c /C+R /I..\dflat
LINK= valx -le -nci $(LINKDEBUG)
#------------------------------------------------

%.obj: %.c:
	$(COMPILE) $*.c

install.exe: install.obj menus.obj uz.obj dialogs.obj
	$(LINK) /STUB:(DOS32a.exe) c0dosw.obj install menus uz dialogs,install,install,..\dflat\dflat.lib cldos.lib

pack.exe: pack.obj
	cc386 /Wc pack.c

dopack: pack.exe install.exe
	copy install.exe pinstall.exe
	pack
	copy pinstall.exe \orangec\dist\occ$(VERNAME)d.exe
