# Software License Agreement
# 
#     Copyright(C) 1994-2018 David Lindauer, (LADSoft)
# 
#     This file is part of the Orange C Compiler package.
# 
#     The Orange C Compiler package is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version, with the addition of the 
#     Orange C "Target Code" exception.
# 
#     The Orange C Compiler package is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
# 
#     contact information:
#         email: TouchStone222@runbox.com <David Lindauer>

DISTRIBUTE:
	$(COPYDIR) 4g\%.exe $(DISTLIB)
	$(COPYDIR) cw\%.exe $(DISTLIB)
	copy cw\read.me $(DISTLIC)\cwstub.lic
	copy d3x\bin\d3xw.exe $(DISTLIB)
	copy d3x\doc\d3x.txt $(DISTLIC)\d3x.lic
	$(COPYDIR) dos32a\%.exe $(DISTLIB)
	copy dos32a\dos32a.lic $(DISTLIC)
	$(COPYDIR) hx\%.zip $(DISTADDON)
	copy hx\hxrt.txt $(DISTLIC)\hxrt.lic
	$(COPYDIR) pmodew\%.exe $(DISTLIB)
	copy pmodew\pmodew.txt $(DISTLIC)\pmodew.lic
	$(COPYDIR) wdos\%.% $(DISTLIB)
	copy wdos\license.txt $(DISTLIC)\wdosx.lic
	$(COPYDIR) zrdx\%.exe $(DISTLIB)
	copy zrdx\readme.txt $(DISTLIC)\zrdx.lic
