#ifndef _APISETCCONV_H
#define _APISETCCONV_H

/* Win32 Calling Conventions for APISETs part of old legacy APIs */

#define WINADVAPI DECLSPEC_IMPORT

#define WINBASEAPI DECLSPEC_IMPORT

#define ZAWPROXYAPI DECLSPEC_IMPORT

#define WINUSERAPI DECLSPEC_IMPORT
#define WINABLEAPI DECLSPEC_IMPORT

#define WINABLEAPI DECLSPEC_IMPORT

#define WINCFGMGR32API DECLSPEC_IMPORT

#define WINDEVQUERYAPI DECLSPEC_IMPORT

#define WINSWDEVICEAPI DECLSPEC_IMPORT

#define CMAPI DECLSPEC_IMPORT

#define WINPATHCCHAPI WINBASEAPI 

#endif /* _APISETCCONV_H */
