#ifndef _COMMAPI_H
#define _COMMAPI_H

#ifdef __ORANGEC__ 
#pragma GCC system_header
#endif

/* ApiSet api-ms-win-core-comm-l1 */

/* #include <apiset.h> */
#include <apisetcconv.h>
#include <windows.h>
#include <winbase.h>
#include <winapifamily.h>

WINBASEAPI BOOL WINAPI ClearCommBreak(HANDLE);
WINBASEAPI BOOL WINAPI ClearCommError(HANDLE, LPDWORD, LPCOMSTAT);
WINBASEAPI BOOL WINAPI SetupComm(HANDLE, DWORD, DWORD);
WINBASEAPI BOOL WINAPI EscapeCommFunction(HANDLE, DWORD);
WINBASEAPI BOOL WINAPI GetCommConfig(HANDLE, LPCOMMCONFIG, LPDWORD);
WINBASEAPI BOOL WINAPI GetCommMask(HANDLE, LPDWORD);
WINBASEAPI BOOL WINAPI GetCommModemStatus(HANDLE, LPDWORD);
WINBASEAPI BOOL WINAPI GetCommProperties(HANDLE, LPCOMMPROP);
WINBASEAPI BOOL WINAPI GetCommState(HANDLE, LPDCB);
WINBASEAPI BOOL WINAPI GetCommTimeouts(HANDLE, LPCOMMTIMEOUTS);
WINBASEAPI BOOL WINAPI PurgeComm(HANDLE, DWORD);
WINBASEAPI BOOL WINAPI SetCommBreak(HANDLE);
WINBASEAPI BOOL WINAPI SetCommConfig(HANDLE, LPCOMMCONFIG, DWORD);
WINBASEAPI BOOL WINAPI SetCommMask(HANDLE, DWORD);
WINBASEAPI BOOL WINAPI SetCommState(HANDLE, LPDCB);
WINBASEAPI BOOL WINAPI SetCommTimeouts(HANDLE, LPCOMMTIMEOUTS);
WINBASEAPI BOOL WINAPI TransmitCommChar(HANDLE, char);
WINBASEAPI BOOL WINAPI WaitCommEvent(HANDLE, LPDWORD, LPOVERLAPPED);

#endif /* _COMMAPI_H */
