/*
    Software License Agreement (BSD License)
    
    Copyright (c) 1997-2011, David Lindauer, (LADSoft).
    All rights reserved.
    
    Redistribution and use of this software in source and binary forms, 
    with or without modification, are permitted provided that the following 
    conditions are met:
    
    * Redistributions of source code must retain the above
      copyright notice, this list of conditions and the
      following disclaimer.
    
    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the
      following disclaimer in the documentation and/or other
      materials provided with the distribution.
    
    * Neither the name of LADSoft nor the names of its
      contributors may be used to endorse or promote products
      derived from this software without specific prior
      written permission of LADSoft.
    
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
    OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
    OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
    OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#define ERR_UNKNOWN 0
#define ERR_TOO_MANY_ERRORS 1
#define ERR_CONSTTOOLARGE 2
#define ERR_CONSTANT_VALUE_EXPECTED 3
#define ERR_INVCONST 4
#define ERR_INVFPCONST 5
#define ERR_INVALID_CHAR_CONSTANT 6
#define ERR_UNTERM_CHAR_CONSTANT 7
#define ERR_INVALID_STRING_CONSTANT 8
#define ERR_UNTERM_STRING_CONSTANT 9
#define ERR_STRING_CONSTANT_TOO_LONG 10
#define ERR_NEEDY 11
#define ERR_NEEDSTRING 12
#define ERR_NEED_CONSTANT_OR_ADDRESS 13
#define ERR_NEED_INTEGER_TYPE 14
#define ERR_NEED_INTEGER_EXPRESSION 15
#define ERR_IDENTIFIER_EXPECTED 16
#define ERR_DUPLICATE_IDENTIFIER 17
#define ERR_UNDEFINED_IDENTIFIER 18
#define ERR_TOO_MANY_IDENTIFIERS 19
#define ERR_UNEXPECTED_EOF 20
#define ERR_EOF_NONTERM 21
#define ERR_EOF_COMMENT 22
#define ERR_EOF_PREPROC 23
#define ERR_PPELIF_NO_IF 24
#define ERR_PPELSE_NO_IF 25
#define ERR_PPENDIF_NO_IF 26
#define ERR_MACROSUBS 27
#define ERR_WRONGMACROARGS 28
#define ERR_EOL_UNEXPECTED 29
#define ERR_UNKNOWNDIR 30
#define ERR_PP_DIR_ERROR 31
#define ERR_INCL_FILE_NAME 32
#define ERR_INCL_CANT_OPEN 33
#define ERR_PP_INV_DEFINITION 34
#define ERR_PP_REDEFINE_NOT_SAME 35
#define ERR_PRAGERROR 36
#define ERR_PRAGWARN 37
#define ERR_PREVIOUS 38
#define ERR_UNKNOWN_CHAR 39
#define ERR_UNSIZED 40
#define ERR_UNSIZED_TYPE 41
#define ERR_MISMATCHED_STRUCTURED_TYPE_IN_REDEFINITION 42
#define ERR_STRUCTURE_BODY_NO_MEMBERS 43
#define ERR_ANONYMOUS_UNION_WARNING 44
#define ERR_ANONYMOUS_STRUCT_WARNING 45
#define ERR_STRUCT_HAS_BODY 46
#define ERR_STRUCT_MAY_NOT_CONTAIN_INCOMPLETE_STRUCT 47
#define ERR_ENUM_CONSTANTS_DEFINED 48
#define ERR_ANSI_ENUM_NO_COMMA 49
#define ERR_ORIGINAL_TYPE_NOT_ENUMERATION 50
#define ERR_ANSI_ENUM_NEEDS_BODY 51
#define ERR_BIT_STRUCT_MEMBER 52
#define ERR_ANSI_INT_BIT 53
#define ERR_BIT_FIELD_INTEGER_TYPE 54
#define ERR_BIT_FIELD_TOO_LARGE 55
#define ERR_BIT_FIELD_MUST_CONTAIN_AT_LEAST_ONE_BIT 56
#define ERR_MEMBER_NAME_EXPECTED 57
#define ERR_POINTER_TO_STRUCTURE_EXPECTED 58
#define ERR_STRUCTURED_TYPE_EXPECTED 59
#define ERR_INVALID_STORAGE_CLASS 60
#define ERR_ABSOLUTE_NEEDS_ADDRESS 61
#define ERR_TOO_MANY_STORAGE_CLASS_SPECIFIERS 62
#define ERR_ANSI_FORBID_BOTH_EXTERN_STATIC 63
#define ERR_INLINE_NO_STATIC 64
#define ERR_INLINE_CANNOT_REFER_TO_STATIC 65
#define ERR_NO_LINKAGE_HERE 66
#define ERR_TOO_MANY_LINKAGE_SPECIFIERS 67
#define ERR_DECLARE_SYNTAX 68
#define ERR_DECLARATION_DIFFERENT_QUALIFIERS 69
#define ERR_NO_DECLARATION_HERE 70
#define ERR_DUPLICATE_TYPE_QUALIFIER 71
#define ERR_MISSING_TYPE_SPECIFIER 72
#define ERR_MISSING_TYPE_FOR_PARAMETER 73
#define ERR_C99_KEYWORD 74
#define ERR_TOO_MANY_TYPE_SPECIFIERS 75
#define ERR_TOO_MANY_IDENTIFIERS_IN_DECLARATION 76
#define ERR_TYPE_C99 77
#define ERR_VOID_NOT_ALLOWED 78
#define ERR_INCOMPATIBLE_TYPE_CONVERSION 79
#define ERR_REDEFINITION_OF_TYPE 80
#define ERR_TOO_MANY_QUALIFIERS 81
#define ERR_TYPE_MISMATCH_IN_REDECLARATION 82
#define ERR_TWO_OPERANDS_SAME_TYPE 83
#define ERR_VLA_c99 84
#define ERR_VLA_BLOCK_SCOPE 85
#define ERR_UNSIZED_VLA_PARAMETER 86
#define ERR_ARRAY_QUALIFIERS_C99 87
#define ERR_QUAL_LAST_ARRAY_ELEMENT 88
#define ERR_ARRAY_QUAL_PARAMETER_ONLY 89
#define ERR_ONLY_FIRST_INDEX_MAY_BE_EMPTY 90
#define ERR_ARRAY_INDEX_INTEGER_TYPE 91
#define ERR_ARRAY_NEED_CLOSEBRACKET 92
#define ERR_INVALID_ARRAY_INDEX 93
#define ERR_ARRAY_INVALID_INDEX 94
#define ERR_EMPTY_ARRAY_LAST 95
#define ERR_ARRAY_EXPECTED 96
#define ERR_ARRAY_INDEX_OUT_OF_RANGE 97
#define ERR_TYPE_MISMATCH_FUNC_DECLARATION 98
#define ERR_FUNCTION_BODY_EXPECTED 99
#define ERR_FUNCTION_PARAMETER_EXPECTED 100
#define ERR_PARAMETER_MUST_HAVE_NAME 101
#define ERR_STRUCT_UNION_NO_FUNCTION 102
#define ERR_FUNCTION_NO_RETURN_FUNCTION_ARRAY 103
#define ERR_FUNCTION_SHOULD_RETURN_VALUE 104
#define ERR_VOID_ONLY_PARAMETER 105
#define ERR_INLINE_NOT_ALLOWED 106
#define ERR_MAIN_CANNOT_BE_INLINE_FUNC 107
#define ERR_FUNCTION_TAKES_NO_PARAMETERS 108
#define ERR_CALL_FUNCTION_NO_PROTO 109
#define ERR_PARAMETER_LIST_TOO_LONG 110
#define ERR_PARAMETER_LIST_TOO_SHORT 111
#define ERR_CALL_OF_NONFUNCTION 112
#define ERR_TYPE_MISMATCH_IN_ARGUMENT 113
#define ERR_EXTERN_NO_INIT 114
#define ERR_TYPEDEF_NO_INIT 115
#define ERR_VLA_NO_INIT 116
#define ERR_TOO_MANY_INITIALIZERS 117
#define ERR_C99_STYLE_INITIALIZATION_USED 118
#define ERR_C99_NON_CONSTANT_INITIALIZATION 119
#define ERR_BIT_NO_INITIAL_VALUE 120
#define ERR_CANNOT_INITIALIZE 121
#define ERR_ABSOLUTE_NOT_INITIALIZED 122
#define ERR_CONSTANT_MUST_BE_INITIALIZED 123
#define ERR_STRING_TYPE_MISMATCH_IN_INITIALIZATION 124
#define ERR_MULTIPLE_INITIALIZATION 125
#define ERR_INITIALIZATION_MAY_BE_BYPASSED 126
#define ERR_GOTO_BYPASSES_VLA_INITIALIZATION 127
#define ERR_NONPORTABLE_POINTER_CONVERSION 128
#define ERR_NONPORTABLE_POINTER_COMPARISON 129
#define ERR_INVALID_POINTER_CONVERSION 130
#define ERR_SUSPICIOUS_POINTER_CONVERSION 131
#define ERR_SHORT_POINTER 132
#define ERR_INVALID_BASE_TYPE_FOR_STRING_CONSTANT 133
#define ERR_LVALUE 134
#define ERR_DEREF 135
#define ERR_USED_WITHOUT_ASSIGNMENT 136
#define ERR_POSSIBLE_INCORRECT_ASSIGNMENT 137
#define ERR_ANSI_FORBIDS_IMPLICIT_CONVERSION_FROM_VOID 138
#define ERR_SYM_ASSIGNED_VALUE_NEVER_USED 139
#define ERR_UNUSED_PARAMETER 140
#define ERR_UNUSED_VARIABLE 141
#define ERR_UNUSED_STATIC 142
#define ERR_VARIABLE_OBSCURES_VARIABLE_AT_HIGHER_SCOPE 143
#define ERR_NOT_AN_ALLOWED_TYPE 144
#define ERR_CANNOT_MODIFY_CONST_OBJECT 145
#define ERR_EXPRESSION_SYNTAX 146
#define ERR_SIGNED_UNSIGNED_MISMATCH_RELAT 147
#define ERR_SIZEOF_NO_FUNCTION 148
#define ERR_ILL_STRUCTURE_ASSIGNMENT 149
#define ERR_ILL_STRUCTURE_OPERATION 150
#define ERR_ILL_USE_OF_COMPLEX 151
#define ERR_ILL_USE_OF_FLOATING 152
#define ERR_ILL_POINTER_OPERATION 153
#define ERR_ILL_POINTER_ADDITION 154
#define ERR_ILL_POINTER_SUBTRACTION 155
#define ERR_CANNOT_TAKE_ADDRESS_OF_BIT_FIELD 156
#define ERR_CANNOT_TAKE_ADDRESS_OF_REGISTER 157
#define ERR_MUST_TAKE_ADDRESS_OF_MEMORY_LOCATION 158
#define ERR_CANNOT_USE_BOOLEAN_HERE 159
#define ERR_HOOK_NEEDS_COLON 160
#define ERR_SWITCH_SELECTION_INTEGRAL 161
#define ERR_BREAK_NO_LOOP 162
#define ERR_CASE_NO_SWITCH 163
#define ERR_DUPLICATE_CASE 164
#define ERR_CASE_INTEGER_CONSTANT 165
#define ERR_CONTINUE_NO_LOOP 166
#define ERR_DEFAULT_NO_SWITCH 167
#define ERR_SWITCH_NEEDS_OPENPA 168
#define ERR_SWITCH_NEEDS_CLOSEPA 169
#define ERR_SWITCH_HAS_DEFAULT 170
#define ERR_DO_STMT_NEEDS_WHILE 171
#define ERR_DOWHILE_NEEDS_OPENPA 172
#define ERR_DOWHILE_NEEDS_CLOSEPA 173
#define ERR_WHILE_NEEDS_OPENPA 174
#define ERR_WHILE_NEEDS_CLOSEPA 175
#define ERR_FOR_NEEDS_SEMI 176
#define ERR_FOR_NEEDS_OPENPA 177
#define ERR_FOR_NEEDS_CLOSEPA 178
#define ERR_IF_NEEDS_OPENPA 179
#define ERR_IF_NEEDS_CLOSEPA 180
#define ERR_MISPLACED_ELSE 181
#define ERR_GOTO_NEEDS_LABEL 182
#define ERR_DUPLICATE_LABEL 183
#define ERR_UNDEFINED_LABEL 184
#define ERR_RETURN_MUST_RETURN_VALUE 185
#define ERR_CANNOT_RETURN_VOID_VALUE 186
#define ERR_RETURN_NO_VALUE 187
#define ERR_RETMISMATCH 188
#define ERR_FUNCTION_RETURNING_ADDRESS_STACK_VARIABLE 189
#define ERR_EXPRESSION_HAS_NO_EFFECT 190
#define ERR_UNEXPECTED_END_OF_BLOCKDATA 191
#define ERR_UNREACHABLE_CODE 192
#define ERR_ANSI_CANNOT_OMIT_SEMI 193
#define ERR_NO_REF_POINTER_REF 194
#define ERR_ARRAY_OF_REFS_NOT_ALLOWED 195
#define ERR_REF_MUST_INITIALIZE 196
#define ERR_REF_INIT_REQUIRES_LVALUE 197
#define ERR_REF_INIT_TYPE_REQUIRES_LVALUE_OF_TYPE 198
#define ERR_REF_CLASS_NO_CONSTRUCTORS 199
#define ERR_REF_NOT_INITIALIZED_IN_CONSTRUCTOR 200
#define ERR_REF_NO_QUALIFIERS 201
#define ERR_REF_RETURN_LOCAL 202
#define ERR_CANNOT_CONVERT_TYPE 203
#define ERR_CANNOT_CAST_TYPE 204
#define ERR_INVALID_USE_OF_NAMESPACE 205
#define ERR_NO_NAMESPACE_IN_FUNCTION 206
#define ERR_NOT_A_NAMESPACE 207
#define ERR_NAMESPACE_NOT_INLINE 208
#define ERR_EXPECTED_NAMESPACE_NAME 209
#define ERR_CYCLIC_USING_DIRECTIVE 210
#define ERR_PURESTRING 211
#define ERR_ASM ERR_PURESTRING
#define ERR_CREATE_TEMPORARY 212
#define ERR_TYPE_NAME_EXPECTED 213
#define ERR_AMBIGUITY_BETWEEN 214
#define ERR_UNKNOWN_LINKAGE 215
#define ERR_CHAR1632_CONSTANT_TOO_LONG 216
#define ERR_EOF_RAW_STRING 217
#define ERR_RAW_STRING_INVALID_CHAR 218
#define ERR_MAIN_CANNOT_BE_STATIC_FUNC 219
#define ERR_MAIN_CANNOT_BE_CONSTEXPR 220
#define ERR_CONSTANT_EXPRESSION_EXPECTED 221
#define ERR_CONSTANT_FUNCTION_EXPECTED 222
#define ERR_CONSTEXPR_REQUIRES_INITIALIZER 223
#define ERR_CONSTEXPR_SIMPLE_TYPE 224
#define ERR_FUNCTION_RETURNING_REF_SHOULD_RETURN_VALUE 225
#define ERR_QUALIFIED_NAME_NOT_ALLOWED_HERE 226
#define ERR_NAME_IS_NOT_A_MEMBER_OF_NAME 227
#define ERR_QUALIFIER_NOT_A_CLASS_OR_NAMESPACE 228
#define ERR_LINKAGE_MISMATCH_IN_FUNC_OVERLOAD 229
#define ERR_OVERLOAD_DIFFERS_ONLY_IN_RETURN_TYPE 230
#define ERR_NO_OVERLOAD_MATCH_FOUND 231
#define ERR_CANNOT_REDECLARE_DEFAULT_ARGUMENT 232
#define ERR_NO_LOCAL_VAR_OR_PARAMETER_DEFAULT_ARGUMENT 233
#define ERR_NO_POINTER_TO_FUNCTION_DEFAULT_ARGUMENT 234
#define ERR_NO_DEFAULT_ARGUMENT_IN_TYPEDEF 235
#define ERR_NO_THIS_DEFAULT_ARGUMENT 236
#define ERR_MISSING_DEFAULT_ARGUMENT 237
#define ERR_DELETE_ON_REDECLARATION 238
#define ERR_DELETED_FUNCTION_REFERENCED 239
#define ERR_MAIN_CANNOT_BE_DELETED 240
#define ERR_ENUMERATION_OUT_OF_RANGE_OF_BASE_TYPE 241
#define ERR_ENUMERATED_TYPE_NEEDS_NAME 242
#define ERR_CANNOT_OMIT_ENUMERATION_BASE 243
#define ERR_REDEFINITION_OF_ENUMERATION_SCOPE_OR_BASE_TYPE 244
#define ERR_CANNOT_DEFINE_ENUMERATION_CONSTANT_HERE 245
#define ERR_SCOPED_TYPE_MISMATCH 246
#define ERR_SIZEOF_BITFIELD 247
#define ERR_SIZEOF_UNFIXED_ENUMERATION 248
#define ERR_AUTO_NEEDS_INITIALIZATION 249
#define ERR_AUTO_NOT_ALLOWED 250
#define ERR_REF_INITIALIZATION_DISCARDS_QUALIFIERS 251
#define ERR_REF_INITIALIZATION_CANNOT_USE_LVALUE_OF_TYPE 252
#define ERR_GLOBAL_ANONYMOUS_UNION_NOT_STATIC 253
#define ERR_UNION_CANNOT_HAVE_BASE_CLASSES 254
#define ERR_UNION_CANNOT_BE_BASE_CLASS 255
#define ERR_CANNOT_REDEFINE_ACCESS_FOR 256
#define ERR_CANNOT_ACCESS 257
#define ERR_NONFUNCTION_CANNOT_BE_DECLARED_VIRTUAL 258
#define ERR_FUNCTION_CAN_HAVE_ONE_FINAL_OR_OVERRIDE 259
#define ERR_NAMESPACE_NO_STRUCT 260
#define ERR_NOT_UNAMBIGUOUS_BASE 261
#define ERR_RETURN_TYPES_NOT_COVARIANT 262
#define ERR_OVERRIDING_FINAL_VIRTUAL_FUNC 263
#define ERR_FUNCTION_DOES_NOT_OVERRIDE 264
#define ERR_AMBIGUOUS_VIRTUAL_FUNCTIONS 265
#define ERR_DELETED_VIRTUAL_FUNC 266
#define ERR_FINAL_BASE_CLASS 267
#define ERR_LOCAL_CLASS_FUNCTION_NEEDS_BODY 268
#define ERR_MEMBER_SAME_NAME_AS_CLASS 269
#define ERR_PURE_SPECIFIER_CONST_ZERO 270
#define ERR_SPECIFIER_VIRTUAL_FUNC 271
#define ERR_FUNCTION_NOT_IN_STRUCT 272
#define ERR_AMBIGUOUS_MEMBER_DEFINITION 273
#define ERR_ACCESS_MEMBER_NO_OBJECT 274
#define ERR_NON_CONST_FUNCTION_CALLED_FOR_CONST_OBJECT 275
#define ERR_BASE_CLASS_INCLUDED_MORE_THAN_ONCE 276
#define ERR_ONLY_MEMBER_CONST_VOLATILE 277
#define ERR_ILLEGAL_USE_OF_MEMBER_PTR 278
#define ERR_NORETURN 279
#define ERR_DUPLICATE_TYPE_IN_GENERIC 280
#define ERR_GENERIC_TOO_MANY_DEFAULTS 281
#define ERR_GENERIC_MISSING_TYPE 282
#define ERR_GENERIC_MISSING_EXPRESSION 283
#define ERR_GENERIC_NOTHING_SELECTED 284
#define ERR_THREAD_LOCAL_INVALID_STORAGE_CLASS 285
#define ERR_THREAD_LOCAL_NOT_AUTO 286
#define ERR_FUNC_NOT_THREAD_LOCAL 287
#define ERR_THREAD_LOCAL_MUST_ALWAYS_APPEAR 288
#define ERR_ATOMIC_TYPE_SPECIFIER_NO_QUALS 289
#define ERR_ATOMIC_NO_FUNCTION_OR_ARRAY 290
#define ERR_CANNOT_REDECLARE_OUTSIDE_CLASS 291
#define ERR_TYPE_DEFINITION_NOT_ALLOWED_HERE 292
#define ERR_POINTER_ARRAY_NOT_FRIENDS 293
#define ERR_DECLARATOR_NOT_ALLOWED_HERE 294
#define ERR_THIS_MEMBER_FUNC 295
#define ERR_INVALID_AS_OPERATOR 296
#define ERR_OPERATOR_MUST_BE_FUNCTION 297
#define ERR_OPERATOR_NEEDS_NO_PARAMETERS 298
#define ERR_OPERATOR_NEEDS_ONE_PARAMETER 299
#define ERR_OPERATOR_NEEDS_ZERO_OR_ONE_PARAMETER 300
#define ERR_OPERATOR_NEEDS_PARAMETER_OF_TYPE_INT 301
#define ERR_OPERATOR_NONSTATIC 302
#define ERR_OPERATOR_NEEDS_A_CLASS_OR_ENUMERATION_PARAMETER 303
#define ERR_OPERATOR_NEEDS_TWO_PARAMETERS 304
#define ERR_OPERATOR_NEEDS_ONE_OR_TWO_PARAMETER 305
#define ERR_OPERATOR_NEEDS_SECOND_PARAMETER_OF_TYPE_INT 306
#define ERR_OPERATOR_MUST_BE_NONSTATIC 307
#define ERR_OPERATOR_RETURN_REFERENCE_OR_POINTER 308
#define ERR_CANNOT_CREATE_INSTANCE_ABSTRACT 309
#define ERR_ABSTRACT_BECAUSE 310
#define ERR_OPERATOR_LITERAL_EMPTY_STRING 311
#define ERR_OPERATOR_LITERAL_NEEDS_ID 312
#define ERR_OPERATOR_LITERAL_NAMESPACE_SCOPE 313
#define ERR_OPERATOR_LITERAL_INVALID_PARAMETER_LIST 314
#define ERR_COULD_NOT_FIND_A_MATCH_FOR_LITERAL_SUFFIX 315
#define ERR_LITERAL_SUFFIX_MISMATCH 316
#define ERR_STRUCT_NOT_DEFINED 317