
all:
	$(MAKE) -Calexcs
	$(MAKE) -Cbzip2-1.0.5
	$(MAKE) -Ccpplinq
	$(MAKE) -Cellf
	$(MAKE) -Cgeneral
	$(MAKE) -Clame
	$(MAKE) -Clibogg-1.2.0
	$(MAKE) -Clibvorbis-1.3.2
	$(MAKE) -Clpng162
	$(MAKE) -Cq
	$(MAKE) -Csqlite3
	$(MAKE) -Cx264
	$(MAKE) -Czlib-1.2.5
