# Software License Agreement
# 
#     Copyright(C) 1994-2025 David Lindauer, (LADSoft)
# 
#     This file is part of the Orange C Compiler package.
# 
#     The Orange C Compiler package is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
# 
#     The Orange C Compiler package is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License
#     along with Orange C.  If not, see <http://www.gnu.org/licenses/>.
# 
#     contact information:
#         email: TouchStone222@runbox.com <David Lindauer>
# 
# 

DISTRIBUTE:
	-copy helpdownloader\bin\release\helpdownloader.exe $(DISTBIN_8)
	-copy helpdownloader\bin\release\helpdownloader.exe.config $(DISTBIN_8)
	-copy helpviewerproject\hv2viewer\bin\release\hv2viewer.exe $(DISTBIN_8)
	-copy helpviewerproject\hv2viewer\bin\release\hv2viewer.exe.config $(DISTBIN_8)
	-copy helpviewerproject\hv2viewer\bin\release\*.dll $(DISTBIN_8)
	-copy helpviewerproject\hv2viewer\bin\debug\branding\*.* $(DISTBIN_8)\branding
	-copy helpviewerproject\hv2viewer\bin\release_7\hv2viewer.exe $(DISTBIN_7)
	-copy helpviewerproject\hv2viewer\bin\release_7\hv2viewer.exe.config $(DISTBIN_7)
	-copy helpviewerproject\hv2viewer\bin\release_7\*.dll $(DISTBIN_7)
	-copy helpviewerproject\hv2viewer\bin\debug\branding\*.* $(DISTBIN_7)\branding
	-copy helpdownloader\*.lic $(DISTLIC)
	-copy helpviewerproject\*.lic $(DISTLIC)