B := py \orangec\lit\lit.py --echo-all-commands

all:
	$(B) std

algorithms:
	$(B) std/algorithms

atomics:
	$(B) std/atomics

containers:
	$(B) std/containers

depr:
	$(B) std/depr

diagnostics:
	$(B) std/diagnostifcs

experimental:
	$(B) std/experimental

input.output:
	$(B) std/input.output

iterators:
	$(B) std/iterators

language.support:
	$(B) std/language.support

localization:
	$(B) std/localization

numerics:
	$(B) std/numerics

pstl:
	$(B) std/pstl

re:
	$(B) std/re

strings:
	$(B) std/strings

thread:
	$(B) std/thread

utilities:
	$(B) std/utilities

