aa bitmap "hi.bmp"
struct aa1 {
    int r,s,t ;
    struct {
       int t;
       char x;
    } bb;
};
cc bitmap "hi.bmp"
EXPORT void ff(int a, int b);
enum aa2 {

    r0,
    r1 = 5,
    r2 = 6,
    r3
};
typedef int aa3;
dd bitmap "hi.bmp"
typedef struct aa4{
	char v;
	int mm;
} hi;

bb bitmap "hi.bmp"

xx nn "hi.bmp"
xx1 nn { 1 , 2, 3, 4 }

rr typedef int int int aaz;
rr1 typedef struct aa bb cc dd { int a; int b; int c; { } };
rr2 struct aa bb cc dd {int a; int b; int c; { } };
rr3 enum bb cc dd { int a; int b; int c; { } };
rr4 enum bb ;
struct zz ;
