#define STRING_VERSION "6.0.51.1"
#define PRODUCT_VERSION 6,0,51,1
#define CLIB_VERSION 6,0,51,1
#define PRODUCT_STRING_VERSION STRING_VERSION
#define PRODUCT_NAME "Orange C Compiler Package"
#define CLIB_STRING_VERSION STRING_VERSION
#define COPYRIGHT "Copyright (C) LADSoft 2006-2021"
#define LIBRARY_COPYRIGHT "Copyright (C) LADSoft 1994-2021"
