C_DEPENDENCIES = $(wildcard *.c)
EXCLUDE= q.c
DEPENDENCIES = $(filter-out $(EXCLUDE), $(C_DEPENDENCIES))
O_DEPENDENCIES = $(DEPENDENCIES:.c=.o)

%.o: %.c
	occ /9 /c /C+d $^

temp.exe: $(O_DEPENDENCIES)
	olink -otemp.exe /T:CON32 /x /c c0xpe.o $(O_DEPENDENCIES) clwin.l climp.l	
