#define ABE_BOTTOM (3)
#define ABE_LEFT (0)
#define ABE_RIGHT (2)
#define ABE_TOP (1)

#define ABM_ACTIVATE (6)
#define ABM_GETAUTOHIDEBAR (7)
#define ABM_GETSTATE (4)
#define ABM_GETTASKBARPOS (5)
#define ABM_NEW (0)
#define ABM_QUERYPOS (2)
#define ABM_REMOVE (1)
#define ABM_SETAUTOHIDEBAR (8)
#define ABM_SETPOS (3)
#define ABM_WINDOWPOSCHANGED (9)

#define ABN_FULLSCREENAPP (2)
#define ABN_POSCHANGED (1)
#define ABN_STATECHANGE (0)
#define ABN_WINDOWARRANGE (3)

#define ABS_ALWAYSONTOP (2)
#define ABS_AUTOHIDE (1)

#ifndef FO_MOVE
#define FOF_ALLOWUNDO (64)
#define FOF_CONFIRMMOUSE (2)
#define FOF_FILESONLY (128)
#define FOF_MULTIDESTFILES (1)
#define FOF_NOCONFIRMATION (16)
#define FOF_NOCONFIRMMKDIR (512)
#define FOF_NOCOPYSECURITYATTRIBS (2048)
#define FOF_NOERRORUI (1024)
#define FOF_NORECURSION (4096)
#define FOF_NO_CONNECTED_ELEMENTS (8192)
#define FOF_RENAMEONCOLLISION (8)
#define FOF_SILENT (4)
#define FOF_SIMPLEPROGRESS (256)
#define FOF_WANTMAPPINGHANDLE (32)
#define FOF_WANTNUKEWARNING (16384)

#define FO_COPY (2)
#define FO_DELETE (3)
#define FO_MOVE (1)
#define FO_RENAME (4)
#define PO_DELETE (19)
#define PO_PORTCHANGE (32)
#define PO_RENAME (20)
#define PO_REN_PORT (52)

#ifndef RC_INVOKED
typedef WORD FILEOP_FLAGS;
typedef WORD PRINTEROP_FLAGS;
#endif

#endif

#define NIF_ICON (2)
#define NIF_INFO (16)
#define NIF_MESSAGE (1)
#define NIF_STATE (8)
#define NIF_TIP (4)

#define NIIF_ERROR (3)
#define NIIF_INFO (1)
#define NIIF_NONE (0)
#define NIIF_WARNING (2)

#define NIM_ADD (0)
#define NIM_DELETE (2)
#define NIM_MODIFY (1)
#define NIM_SETFOCUS (3)
#define NIM_SETVERSION (4)

#define NINF_KEY (1)

#define NIN_KEYSELECT (NIN_SELECT | NINF_KEY)
#define NIN_SELECT (1024)

#define NIS_HIDDEN (1)
#define NIS_SHAREDICON (2)

#define NOTIFYICON_VERSION (3)

#define PRINTACTION_DOCUMENTDEFAULTS (6)
#define PRINTACTION_NETINSTALL (2)
#define PRINTACTION_NETINSTALLLINK (3)
#define PRINTACTION_OPEN (0)
#define PRINTACTION_OPENNETPRN (5)
#define PRINTACTION_PROPERTIES (1)
#define PRINTACTION_SERVERPROPERTIES (7)
#define PRINTACTION_TESTPAGE (4)

#define SEE_MASK_ASYNCOK (1048576)
#define SEE_MASK_CLASSKEY (3)
#define SEE_MASK_CLASSNAME (1)
#define SEE_MASK_CONNECTNETDRV (128)
#define SEE_MASK_DOENVSUBST (512)
#define SEE_MASK_FLAG_DDEWAIT (256)
#define SEE_MASK_FLAG_NO_UI (1024)
#define SEE_MASK_HMONITOR (2097152)
#define SEE_MASK_HOTKEY (32)
#define SEE_MASK_ICON (16)
#define SEE_MASK_IDLIST (4)
#define SEE_MASK_INVOKEIDLIST (12)
#define SEE_MASK_NOCLOSEPROCESS (64)
#define SEE_MASK_NOQUERYCLASSSTORE (16777216)
#define SEE_MASK_NO_CONSOLE (32768)
#define SEE_MASK_UNICODE (16384)
#define SEE_MASK_WAITFORINPUTIDLE (33554432)

#define SE_ERR_ACCESSDENIED (5)
#define SE_ERR_ASSOCINCOMPLETE (27)
#define SE_ERR_DDEBUSY (30)
#define SE_ERR_DDEFAIL (29)
#define SE_ERR_DDETIMEOUT (28)
#define SE_ERR_DLLNOTFOUND (32)
#define SE_ERR_FNF (2)
#define SE_ERR_NOASSOC (31)
#define SE_ERR_OOM (8)
#define SE_ERR_PNF (3)
#define SE_ERR_SHARE (26)

#define SHARD_PIDL	1
#define SHARD_PATH  2

#define SHERB_NOCONFIRMATION (1)
#define SHERB_NOPROGRESSUI (2)
#define SHERB_NOSOUND (4)

#define SHGFI_ADDOVERLAYS (32)
#define SHGFI_ATTRIBUTES (2048)
#define SHGFI_ATTR_SPECIFIED (131072)
#define SHGFI_DISPLAYNAME (512)
#define SHGFI_EXETYPE (8192)
#define SHGFI_ICON (256)
#define SHGFI_ICONLOCATION (4096)
#define SHGFI_LARGEICON (0)
#define SHGFI_LINKOVERLAY (32768)
#define SHGFI_OPENICON (2)
#define SHGFI_OVERLAYINDEX (64)
#define SHGFI_PIDL (8)
#define SHGFI_SELECTED (65536)
#define SHGFI_SHELLICONSIZE (4)
#define SHGFI_SMALLICON (1)
#define SHGFI_SYSICONINDEX (16384)
#define SHGFI_TYPENAME (1024)
#define SHGFI_USEFILEATTRIBUTES (16)

#define SHGNLI_NOUNIQUE (4)
#define SHGNLI_PIDL (1)
#define SHGNLI_PREFIXNAME (2)

#ifndef WINSHELLAPI
#define WINSHELLAPI       DECLSPEC_IMPORT
#endif // WINSHELLAPI

#ifndef SHSTDAPI
#define SHSTDAPI          DECLSPEC_IMPORT HRESULT STDAPICALLTYPE
#define SHSTDAPI_(type)   DECLSPEC_IMPORT type STDAPICALLTYPE
#endif // SHSTDAPI

#ifndef SHDOCAPI
#define SHDOCAPI          DECLSPEC_IMPORT HRESULT STDAPICALLTYPE
#define SHDOCAPI_(type)   DECLSPEC_IMPORT type STDAPICALLTYPE
#endif // SHDOCAPI
