#define DECLARE_HANDLE32 DECLARE_HANDLE

#define WM_CTLCOLOR (25)
#define WM_CTLCOLORBTN (309)
#define WM_CTLCOLORDLG (310)
#define WM_CTLCOLOREDIT (307)
#define WM_CTLCOLORLISTBOX (308)
#define WM_CTLCOLORMSGBOX (306)
#define WM_CTLCOLORSCROLLBAR (311)
#define WM_CTLCOLORSTATIC (312)

