/*
    Software License Agreement (BSD License)
    
    Copyright (c) 1997-2011, David Lindauer, (LADSoft).
    All rights reserved.
    
    Redistribution and use of this software in source and binary forms, 
    with or without modification, are permitted provided that the following 
    conditions are met:
    
    * Redistributions of source code must retain the above
      copyright notice, this list of conditions and the
      following disclaimer.
    
    * Redistributions in binary form must reproduce the above
      copyright notice, this list of conditions and the
      following disclaimer in the documentation and/or other
      materials provided with the distribution.
    
    * Neither the name of LADSoft nor the names of its
      contributors may be used to endorse or promote products
      derived from this software without specific prior
      written permission of LADSoft.
    
    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
    AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, 
    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR 
    PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER 
    OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, 
    EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
    PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; 
    OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
    WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR 
    OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
    ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

*/

#define ERR_UNKNOWN 0
#define ERR_TOO_MANY_ERRORS 1
#define ERR_CONSTTOOLARGE 2
#define ERR_CONSTANT_VALUE_EXPECTED 3
#define ERR_INVCONST 4
#define ERR_INVFPCONST 5
#define ERR_INVALID_CHAR_CONSTANT 6
#define ERR_UNTERM_CHAR_CONSTANT 7
#define ERR_INVALID_STRING_CONSTANT 8
#define ERR_UNTERM_STRING_CONSTANT 9
#define ERR_STRING_CONSTANT_TOO_LONG 10
#define ERR_NEEDY 11
#define ERR_NEEDSTRING 12
#define ERR_NEED_CONSTANT_OR_ADDRESS 13
#define ERR_NEED_INTEGER_TYPE 14
#define ERR_NEED_INTEGER_EXPRESSION 15
#define ERR_IDENTIFIER_EXPECTED 16
#define ERR_DUPLICATE_IDENTIFIER 17
#define ERR_UNDEFINED_IDENTIFIER 18
#define ERR_TOO_MANY_IDENTIFIERS 19
#define ERR_UNEXPECTED_EOF 20
#define ERR_EOF_NONTERM 21
#define ERR_EOF_COMMENT 22
#define ERR_EOF_PREPROC 23
#define ERR_PPELIF_NO_IF 24
#define ERR_PPELSE_NO_IF 25
#define ERR_PPENDIF_NO_IF 26
#define ERR_MACROSUBS 27
#define ERR_WRONGMACROARGS 28
#define ERR_EOL_UNEXPECTED 29
#define ERR_UNKNOWNDIR 30
#define ERR_PP_DIR_ERROR 31
#define ERR_INCL_FILE_NAME 32
#define ERR_INCL_CANT_OPEN 33
#define ERR_PP_INV_DEFINITION 34
#define ERR_PP_REDEFINE_NOT_SAME 35
#define ERR_PRAGERROR 36
#define ERR_PRAGWARN 37
#define ERR_PREVIOUS 38
#define ERR_UNKNOWN_CHAR 39
#define ERR_UNSIZED 40
#define ERR_UNSIZED_TYPE 41
#define ERR_MISMATCHED_STRUCTURED_TYPE_IN_REDEFINITION 42
#define ERR_STRUCTURE_BODY_NO_MEMBERS 43
#define ERR_ANONYMOUS_UNION_WARNING 44
#define ERR_ANONYMOUS_STRUCT_WARNING 45
#define ERR_STRUCT_HAS_BODY 46
#define ERR_STRUCT_MAY_NOT_CONTAIN_INCOMPLETE_STRUCT 47
#define ERR_ENUM_CONSTANTS_DEFINED 48
#define ERR_ANSI_ENUM_NO_COMMA 49
#define ERR_ORIGINAL_TYPE_NOT_ENUMERATION 50
#define ERR_ANSI_ENUM_NEEDS_BODY 51
#define ERR_BIT_STRUCT_MEMBER 52
#define ERR_ANSI_INT_BIT 53
#define ERR_BIT_FIELD_INTEGER_TYPE 54
#define ERR_BIT_FIELD_TOO_LARGE 55
#define ERR_BIT_FIELD_MUST_CONTAIN_AT_LEAST_ONE_BIT 56
#define ERR_MEMBER_NAME_EXPECTED 57
#define ERR_POINTER_TO_STRUCTURE_EXPECTED 58
#define ERR_STRUCTURED_TYPE_EXPECTED 59
#define ERR_INVALID_STORAGE_CLASS 60
#define ERR_ABSOLUTE_NEEDS_ADDRESS 61
#define ERR_TOO_MANY_STORAGE_CLASS_SPECIFIERS 62
#define ERR_ANSI_FORBID_BOTH_EXTERN_STATIC 63
#define ERR_INLINE_NO_STATIC 64
#define ERR_INLINE_CANNOT_REFER_TO_STATIC 65
#define ERR_NO_LINKAGE_HERE 66
#define ERR_TOO_MANY_LINKAGE_SPECIFIERS 67
#define ERR_DECLARE_SYNTAX 68
#define ERR_NO_DECLARATION_HERE 69
#define ERR_DUPLICATE_TYPE_QUALIFIER 70
#define ERR_MISSING_TYPE_SPECIFIER 71
#define ERR_MISSING_TYPE_FOR_PARAMETER 72
#define ERR_C99_KEYWORD 73
#define ERR_TOO_MANY_TYPE_SPECIFIERS 74
#define ERR_TOO_MANY_IDENTIFIERS_IN_DECLARATION 75
#define ERR_TYPE_C99 76
#define ERR_VOID_NOT_ALLOWED 77
#define ERR_INCOMPATIBLE_TYPE_CONVERSION 78
#define ERR_REDEFINITION_OF_TYPE 79
#define ERR_TOO_MANY_QUALIFIERS 80
#define ERR_TYPE_MISMATCH_IN_REDECLARATION 81
#define ERR_TWO_OPERANDS_SAME_TYPE 82
#define ERR_VLA_c99 83
#define ERR_VLA_BLOCK_SCOPE 84
#define ERR_UNSIZED_VLA_PARAMETER 85
#define ERR_ARRAY_QUALIFIERS_C99 86
#define ERR_QUAL_LAST_ARRAY_ELEMENT 87
#define ERR_ARRAY_QUAL_PARAMETER_ONLY 88
#define ERR_ONLY_FIRST_INDEX_MAY_BE_EMPTY 89
#define ERR_ARRAY_INDEX_INTEGER_TYPE 90
#define ERR_ARRAY_NEED_CLOSEBRACKET 91
#define ERR_INVALID_ARRAY_INDEX 92
#define ERR_ARRAY_INVALID_INDEX 93
#define ERR_EMPTY_ARRAY_LAST 94
#define ERR_ARRAY_EXPECTED 95
#define ERR_ARRAY_INDEX_OUT_OF_RANGE 96
#define ERR_TYPE_MISMATCH_FUNC_DECLARATION 97
#define ERR_FUNCTION_BODY_EXPECTED 98
#define ERR_FUNCTION_PARAMETER_EXPECTED 99
#define ERR_PARAMETER_MUST_HAVE_NAME 100
#define ERR_STRUCT_UNION_NO_FUNCTION 101
#define ERR_FUNCTION_NO_RETURN_FUNCTION_ARRAY 102
#define ERR_FUNCTION_SHOULD_RETURN_VALUE 103
#define ERR_VOID_ONLY_PARAMETER 104
#define ERR_ONLY_FUNCTIONS_INLINE 105
#define ERR_MAIN_CANNOT_BE_INLINE_FUNC 106
#define ERR_FUNCTION_TAKES_NO_PARAMETERS 107
#define ERR_CALL_FUNCTION_NO_PROTO 108
#define ERR_PARAMETER_LIST_TOO_LONG 109
#define ERR_PARAMETER_LIST_TOO_SHORT 110
#define ERR_CALL_OF_NONFUNCTION 111
#define ERR_TYPE_MISMATCH_IN_ARGUMENT 112
#define ERR_EXTERN_NO_INIT 113
#define ERR_TYPEDEF_NO_INIT 114
#define ERR_VLA_NO_INIT 115
#define ERR_TOO_MANY_INITIALIZERS 116
#define ERR_C99_STYLE_INITIALIZATION_USED 117
#define ERR_C99_NON_CONSTANT_INITIALIZATION 118
#define ERR_BIT_NO_INITIAL_VALUE 119
#define ERR_CANNOT_INITIALIZE 120
#define ERR_ABSOLUTE_NOT_INITIALIZED 121
#define ERR_CONSTANT_MUST_BE_INITIALIZED 122
#define ERR_STRING_TYPE_MISMATCH_IN_INITIALIZATION 123
#define ERR_MULTIPLE_INITIALIZATION 124
#define ERR_INITIALIZATION_MAY_BE_BYPASSED 125
#define ERR_GOTO_BYPASSES_VLA_INITIALIZATION 126
#define ERR_NONPORTABLE_POINTER_CONVERSION 127
#define ERR_NONPORTABLE_POINTER_COMPARISON 128
#define ERR_INVALID_POINTER_CONVERSION 129
#define ERR_SUSPICIOUS_POINTER_CONVERSION 130
#define ERR_SHORT_POINTER 131
#define ERR_INVALID_BASE_TYPE_FOR_STRING_CONSTANT 132
#define ERR_LVALUE 133
#define ERR_DEREF 134
#define ERR_USED_WITHOUT_ASSIGNMENT 135
#define ERR_POSSIBLE_INCORRECT_ASSIGNMENT 136
#define ERR_ANSI_FORBIDS_IMPLICIT_CONVERSION_FROM_VOID 137
#define ERR_SYM_ASSIGNED_VALUE_NEVER_USED 138
#define ERR_UNUSED_PARAMETER 139
#define ERR_UNUSED_VARIABLE 140
#define ERR_UNUSED_STATIC 141
#define ERR_VARIABLE_OBSCURES_VARIABLE_AT_HIGHER_SCOPE 142
#define ERR_VALUE_OF_VOID_NOT_ALLOWED 143
#define ERR_CANNOT_MODIFY_CONSTANT 144
#define ERR_EXPRESSION_SYNTAX 145
#define ERR_SIGNED_UNSIGNED_MISMATCH_RELAT 146
#define ERR_SIZEOF_NO_FUNCTION 147
#define ERR_ILL_STRUCTURE_ASSIGNMENT 148
#define ERR_ILL_STRUCTURE_OPERATION 149
#define ERR_ILL_USE_OF_COMPLEX 150
#define ERR_ILL_USE_OF_FLOATING 151
#define ERR_ILL_POINTER_OPERATION 152
#define ERR_ILL_POINTER_ADDITION 153
#define ERR_ILL_POINTER_SUBTRACTION 154
#define ERR_CANNOT_TAKE_ADDRESS_OF_BIT_FIELD 155
#define ERR_CANNOT_TAKE_ADDRESS_OF_REGISTER 156
#define ERR_MUST_TAKE_ADDRESS_OF_MEMORY_LOCATION 157
#define ERR_CANNOT_USE_BOOLEAN_HERE 158
#define ERR_HOOK_NEEDS_COLON 159
#define ERR_SWITCH_SELECTION_INTEGRAL 160
#define ERR_BREAK_NO_LOOP 161
#define ERR_CASE_NO_SWITCH 162
#define ERR_DUPLICATE_CASE 163
#define ERR_CASE_INTEGER_CONSTANT 164
#define ERR_CONTINUE_NO_LOOP 165
#define ERR_DEFAULT_NO_SWITCH 166
#define ERR_SWITCH_NEEDS_OPENPA 167
#define ERR_SWITCH_NEEDS_CLOSEPA 168
#define ERR_SWITCH_HAS_DEFAULT 169
#define ERR_DO_STMT_NEEDS_WHILE 170
#define ERR_DOWHILE_NEEDS_OPENPA 171
#define ERR_DOWHILE_NEEDS_CLOSEPA 172
#define ERR_WHILE_NEEDS_OPENPA 173
#define ERR_WHILE_NEEDS_CLOSEPA 174
#define ERR_FOR_NEEDS_SEMI 175
#define ERR_FOR_NEEDS_OPENPA 176
#define ERR_FOR_NEEDS_CLOSEPA 177
#define ERR_IF_NEEDS_OPENPA 178
#define ERR_IF_NEEDS_CLOSEPA 179
#define ERR_MISPLACED_ELSE 180
#define ERR_GOTO_NEEDS_LABEL 181
#define ERR_DUPLICATE_LABEL 182
#define ERR_UNDEFINED_LABEL 183
#define ERR_RETURN_MUST_RETURN_VALUE 184
#define ERR_CANNOT_RETURN_VOID_VALUE 185
#define ERR_RETURN_NO_VALUE 186
#define ERR_RETMISMATCH 187
#define ERR_FUNCTION_RETURNING_ADDRESS_STACK_VARIABLE 188
#define ERR_EXPRESSION_HAS_NO_EFFECT 189
#define ERR_UNEXPECTED_END_OF_BLOCKDATA 190
#define ERR_UNREACHABLE_CODE 191
#define ERR_ANSI_CANNOT_OMIT_SEMI 192
#define ERR_NO_REF_POINTER_REF 193
#define ERR_ARRAY_OF_REFS_NOT_ALLOWED 194
#define ERR_REF_MUST_INITIALIZE 195
#define ERR_REF_INIT_REQUIRES_LVALUE 196
#define ERR_REF_INIT_TYPE_REQUIRES_LVALUE_OF_TYPE 197
#define ERR_REF_CLASS_NO_CONSTRUCTORS 198
#define ERR_REF_NOT_INITIALIZED_IN_CONSTRUCTOR 199
#define ERR_CANNOT_CONVERT_TYPE 200
#define ERR_CANNOT_CAST_TYPE 201
#define ERR_INVALID_USE_OF_NAMESPACE 202
#define ERR_NO_NAMESPACE_IN_FUNCTION 203
#define ERR_NOT_A_NAMESPACE 204
#define ERR_ASM 205
