name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ORANGEC: d:\a\orangec\orangec
      GITHUB_PATH: d:\a\orangec\orangec\bin
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Configs

    - name: Build
      run: d:\a\orangec\orangec\src\omake -Cd:\a\orangec\orangec\src /DCOMPILER=MS /DORANGEC_ONLY=YES fullbuild -j:2

    - name: Test
      run: |
          echo "d:\a\orangec\orangec\bin" >> "${GITHUB_PATH}"
          d:\a\orangec\orangec\src\omake -Cd:\a\orangec\orangec\tests  -B -j:2 /DCOMPILER=OCC
