name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ORANGEC: /orangec
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Config
      run: echo '\orangec\bin' >> "${GITHUB_PATH}"

    - name: Build
      run: |
         cd src
         omake /DCOMPILER=MS /DORANGEC_ONLY=YES fullbuild -j:2
         cd ..

    - name: Test
      run: |
         cd tests
         omake -B -j:2 /DCOMPILER=OCC
         cd ..
