name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ORANGEC: $env:GITHUB_WORKSPACE

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build
      run: |
          echo "$env:GITHUB_WORKSPACE/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "$env:GITHUB_WORKSPACE/src/omake" "-C$env:GITHUB_WORKSPACE/src" /DCOMPILER=MS /DORANGEC_ONLY=YES fullbuild -j:2
    - name: Test
      run: |
          echo "$env:GITHUB_WORKSPACE/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          "$env:GITHUB_WORKSPACE/src/omake" "-C$env:GITHUB_WORKSPACE/tests"  -B -j:2 /DCOMPILER=OCC
