name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ORANGEC: d:\a\orangec\orangec

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build
      run: |
          echo "d:/a/orangec/orangec/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          d:\a\orangec\orangec\src\omake -Cd:\a\orangec\orangec\src /DCOMPILER=MS /DORANGEC_ONLY=YES fullbuild -j:2
    - name: Test
      run: |
          echo "d:/a/orangec/orangec/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          d:\a\orangec\orangec\src\omake -Cd:\a\orangec\orangec\tests  -B -j:2 /DCOMPILER=OCC
