name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    env:
      ORANGEC: $env:GITHUB_WORKSPACE

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build
      run: |
          &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/src" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" /DCOMPILER=MS /DORANGEC_ONLY=YES fullbuild -j:4
    - name: Test
      run: |
          &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests"  -B -j:4 PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" /DCOMPILER=OCC
