name: windows tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    timeout-minutes : 30

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/checkout@v3
      with:
        repository: c-testsuite/c-testsuite
        path: c-testsuite
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Config
      run: copy "$env:GITHUB_WORKSPACE/c-testsuite/tests/single-exec/*.*" "$env:GITHUB_WORKSPACE/tests/c-testsuite" > NUL
    - name: Build
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/src" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=MS fullbuild -j:8
    - name: Orange C Test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests" -j:8 PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: occil test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occil" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: occpr test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occpr" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occpr" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: LIBCXX tests
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/src" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC test