name: windows smoke test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    timeout-minutes : 30

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/checkout@v4
      with:
        repository: c-testsuite/c-testsuite
        path: c-testsuite
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Config
      run: copy "$env:GITHUB_WORKSPACE/c-testsuite/tests/single-exec/*.*" "$env:GITHUB_WORKSPACE/tests/c-testsuite" > NUL
    - name: Build
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/src" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=MS /DWITHOUT_ZIP=YES fullbuild -j:8
    - name: Orange C Test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests"  -j:8 PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: occil test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occil" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: occpr test
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occpr" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/tests/occpr" PATH="$env:PATH;$env:GITHUB_WORKSPACE/bin" ORANGEC="$env:GITHUB_WORKSPACE" /DCOMPILER=OCC
    - name: Create Artifacts
      run: |
         &$env:GITHUB_WORKSPACE/src/omake "-C$env:GITHUB_WORKSPACE/src" ORANGEC="$env:GITHUB_WORKSPACE" zip
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Binaries
        path: dist/ZippedBinaries.zip
    - name: Update Nightly Release
      if: github.event_name != 'pull_request'
      run: |
        gh release upload --clobber Nightly dist/ZippedBinaries.zip#WindowsBinaries dist/ZippedSources.zip#Sources
        gh release edit --notes-file src/CurrentChanges.md Nightly
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
